config/routes.rb
Rails.application.routes.draw do
  
  get 'moneys/index'
  get 'moneys/show'
  get 'moneys/new'
  post 'moneys/new'
  get 'moneys/edit'
  devise_for :users
  get 'homes/top',as:'routes'
  root to:"homes#top"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    moneys_index_path
  end
  
  def after_sign_out_path_for(resource)
    routes_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/moneys_controller.rb
class MoneysController < ApplicationController
  def index
    @payment = Payment.all
    @income = Income.all
    @chart = Payment.order('created_at ASC')
    @charts = Income.order('created_at ASC')
  end

  def show
    @chart = Payment.order('created_at ASC')
    @charts = Income.order('created_at ASC')
  end

  def new
    @payment = Payment.new
    @income = Income.new
  end
  
  def created
    
  end

  def edit
    @payment = Payment.find(params[:id])
    @icome = Income.find(params[:id])
  end
  
  
  private

  def payment_params
    params.require(:payment).permit(:user_id, :food, :daily, :transportation, :fashion, :hobby, :oyhers, :start_time)
  end
  
  def income_params
    params.require(:income).permit(:user_id, :salary, :invesotment, :sidejob, :other, :start_time)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/moneys_helper.rb
module MoneysHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/moneys/edit.html.erb
<%= render '/header' %>

<h1>収支記録の編集</h1>

<h2>支払登録</h2>
　<%= form_with model: @payment, url: moneys_new_path, method: :post do |f| %>
    <div>
      <%= f.label :日 %>
      <%= f.date_field :start_time %>
    </div>
    <div>
      <%= f.label :内訳%>
      <%= f.select :breakdown, [["食費", "食費"], ["日用品", "日用品"], ["交通費", "交通費"], ["ファッション", "ファッション"],["趣味・娯楽","趣味・娯楽"],["その他","その他"]], include_blank: "選択して下さい" %>
    </div>
    <div>
      <%= f.label :金額 %>
      <%= f.text_field :money %>円
    </div>
    <div>
      <%= f.submit '送信'%>
    </div>
  <% end %>

<h2>収入登録</h2>
  <%= form_with model: @income, url: moneys_new_path, method: :post do |f| %>
    <div>
      <%= f.label :日 %>
      <%= f.date_field :start_time %>
    </div>
    <div>
      <%= f.label :内訳%>
      <%= f.select :breakdown, [["給与", "給与"], ["賞与", "賞与"], ["投資", "投資"], ["副業", "副業"],["趣味・娯楽"],["その他","その他"]], include_blank: "選択して下さい" %>
    </div>
    <div>
      <%= f.label :金額 %>
      <%= f.text_field :money %>円
    </div>
    <div>
      <%= f.submit '送信'%>
    </div>
  <% end %>

app/views/moneys/index.html.erb
<%= render '/header' %>

<h1><%= current_user.name %>さんの収支記録</h1>

<div>
  収入　<%= @payment %>円
</div>
<div>
  支出　<%= @income %>円
</div>

<div>
  今月の収支
</div>

<div>
  <%= link_to "詳細を見る", moneys_show_path %>
</div>

app/views/moneys/new.html.erb
<%= render '/header' %>

<h1>収支記録の追加</h1>

<h2>支払登録</h2>
　<%= form_with model: @payment, url: moneys_new_path, method: :post do |f| %>
    <div>
      <%= f.label :日 %>
      <%= f.date_field :start_time %>
    </div>
    <div>
      <%= f.label :内訳%>
      <%= f.select :breakdown, [["食費", "食費"], ["日用品", "日用品"], ["交通費", "交通費"], ["ファッション", "ファッション"],["趣味・娯楽","趣味・娯楽"],["その他","その他"]], include_blank: "選択して下さい" %>
    </div>
    <div>
      <%= f.label :金額 %>
      <%= f.text_field :money %>円
    </div>
    <div>
      <%= f.submit '送信'%>
    </div>
  <% end %>

<h2>収入登録</h2>
  <%= form_with model: @income, url: moneys_new_path, method: :post do |f| %>
    <div>
      <%= f.label :日 %>
      <%= f.date_field :start_time %>
    </div>
    <div>
      <%= f.label :内訳%>
      <%= f.select :breakdown, [["給与", "給与"], ["賞与", "賞与"], ["投資", "投資"], ["副業", "副業"],["趣味・娯楽"],["その他","その他"]], include_blank: "選択して下さい" %>
    </div>
    <div>
      <%= f.label :金額 %>
      <%= f.text_field :money %>円
    </div>
    <div>
      <%= f.submit '送信'%>
    </div>
  <% end %>

app/views/moneys/show.html.erb
<%= render '/header' %>

<h1>収支記録の詳細</h1>

<div>今月の収入</div>

<div>
  <%= pie_chart @chart %>
</div>
<div>
  給与　<%= @payment %>円
</div>
<div>
  投資　<%= @payment %>円
</div>
<div>
  副業　<%= @payment %>円
</div>
<div>
  その他　<%= @payment %>円
</div>

<div>今月の支出</div>

<div>
  <%= pie_chart @charts %>
</div>
<div>
  食費　<%= @income %>円
</div>
<div>
  日用品　<%= @income %>円
</div>
<div>
  交通費　<%= @income %>円
</div>
<div>
  ファッション　<%= @income %>円
</div>
<div>
  趣味・娯楽　<%= @income %>円
</div>
<div>
  その他　<%= @income %>円
</div>

<div>
  <%= pie_chart @charts %>
</div>

<div>
  <%= link_to "編集する", moneys_edit_path %>
</div>